base_url = "https://grape.surgery"
title = "ğŸ‡ğŸ’‰"
description = "my web site"
default_language = "en"
author = "Zack"
build_search_index = true
compile_sass = true

[markdown]
external_links_target_blank = true
lazy_async_image = true
bottom_footnotes = true
highlight_code = true

[slugify]
paths_keep_dates = true

[extra]
preview_length = 150